# -*- coding: utf-8 -*-
"""Survivor AI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/lf20849/f5a8b7abe2fbd0e6351ea6ef4e6a4887/survivor-ai.ipynb
"""

print("This is program to show propability of Titanic crash")

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io

df = pd.read_csv(io.StringIO(uploaded['train.csv'].decode('utf-8')))
df

df.dtypes

df.drop(["Name","Ticket","Fare","SibSp"], axis=1)



