# -*- coding: utf-8 -*-
"""Survivor AI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YKo9dr_db_EjfJenahBZQkNsgfVL_ZXM
"""

print("This is program to show propability of Titanic crash")

! git clone https://github.com/lf20849/Titanic-Survivor-AI.git

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import io
import seaborn as sns
import missingno as msno
import matplotlib
import matplotlib.pyplot as plt
# %matplotlib inline
matplotlib.style.use('ggplot')

df = pd.read_csv('Titanic-Survivor-AI/titanic/train.csv')
df.head(819)

"""# New section"""

df.dtypes

Gf = pd.DataFrame(abs(df.corr()['Survived']).sort_values(ascending=False))

Gf.plot.line()
Gf.plot.scatter(x='Fare', y='Survived', c='DarkBlue')

corrMatrix = df.corr()
sns.heatmap(corrMatrix, annot=True)
plt.show()

s = pd.Series(Gp)
s.plot.line()

df.drop(["Name","Ticket","Cabin","SibSp"], axis=1)

df[["Sex", "Survived"]].groupby(['Sex'], as_index= False).mean().sort_values(by='Survived', ascending = False)

df[["Age", "Survived"]].groupby(['Age'], as_index= False).mean().sort_values(by='Age', ascending = True)

df[["Pclass", "Survived"]].groupby(['Pclass'], as_index= False).mean().sort_values(by='Pclass', ascending = True)

df[["Fare", "Survived"]].groupby(['Fare'], as_index= False).mean().sort_values(by='Fare', ascending = False)

df[["Cabin", "Survived"]].groupby(['Cabin'], as_index= False).mean().sort_values(by='Survived', ascending = False)

df[["SibSp", "Survived"]].groupby(['SibSp'], as_index= False).mean().sort_values(by='SibSp', ascending = True)

df[["Parch", "Survived"]].groupby(['Parch'], as_index= False).mean().sort_values(by='Parch', ascending = True)

df[["Embarked", "Survived"]].groupby(['Embarked'], as_index= False).mean().sort_values(by='Embarked', ascending = True)

sns.heatmap(df.isnull(), cbar=False)

msno.matrix(df)

df.info()

df.plot.scatter(x="Survived", y="Fare")